import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import clientPromise from '../lib/mongodb'
import TodoItem from './todoItem'
import InputField from './inputField.tsx'

export default function Home({todos}) {
  console.log(todos)
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={'mb-10 text-6xl'}>
          Tasker
        </h1>
        {/* todos go here */}
        <InputField />
        <div className={styles.grid}>
          
          <TodoItem title="My Todo Item" text='Write More Documentation'/>
          <TodoItem title="My Todo Item 2" text='Write Better Documentation'/>
          <TodoItem title="My Todo Item 3" text='Write Cooler Documentation'/>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
export async function getServerSideProps(context) {
  try {
    const client = await clientPromise
    const db = client.db('todo')
    let todos = await db.collection('todos').find({}).toArray()
    todos = JSON.stringify(todos)

    return {
      props: { todos: todos,
              isConnected: true },
    }
  } catch (e) {
    console.error(e)
    return {
      props: { isConnected: false },
    }
  }
}